fix token duplication in frontend
langchain-ai/chat-langchain pull request #301
Opened 2024-04-22 19:45 UTC by spatker

applyPatch modifies the document so every token got added twice to the stream

Fixes: #300

2024-04-28 14:44 UTC, Trde654 reviewed
😍😘✌️

2024-04-28 14:44 UTC, Trde654 commented on frontend/app/components/ChatWindow.tsx
> +        streamedResponse = applyPatch(streamedResponse, chunk.ops, undefined, false).newDocument;
Yes

2024-04-28 14:49 UTC, luca-git commented on frontend/app/components/ChatWindow.tsx
> +        streamedResponse = applyPatch(streamedResponse, chunk.ops, undefined, false).newDocument;
That works!

2024-04-29 03:25 UTC, Trde654 reviewed
Traducción

2024-04-29 03:25 UTC, Trde654 commented on frontend/app/components/ChatWindow.tsx
> +        streamedResponse = applyPatch(streamedResponse, chunk.ops, undefined, false).newDocument;
**@😘**

2024-04-29 03:28 UTC, Trde654 requested changes
Traidora

2024-04-29 03:28 UTC, Trde654 commented on frontend/app/components/ChatWindow.tsx
> +        streamedResponse = applyPatch(streamedResponse, chunk.ops, undefined, false).newDocument;
Traidora

2024-04-29 03:28 UTC, Trde654 reviewed
❤️

2024-04-29 04:11 UTC, Trde654 reviewed
@agola11

2024-04-29 04:11 UTC, Trde654 commented on frontend/app/components/ChatWindow.tsx
> +        streamedResponse = applyPatch(streamedResponse, chunk.ops, undefined, false).newDocument;
****

2024-04-29 04:11 UTC, Trde654 commented on frontend/app/components/ChatWindow.tsx
> +        streamedResponse = applyPatch(streamedResponse, chunk.ops, undefined, false).newDocument;
@spatker

2024-05-01 15:13 UTC, Trde654 reviewed
Traducción

2024-05-22 23:22 UTC, vbarda approved these changes

2024-05-22 23:26 UTC, vbarda commented
Thank you @spatker!

2024-05-22 23:26 UTC, merged